In [11]:
# numpy is used to import array in python to use features of array in python
#provides 
#an array object of arbitrary homogeneous items
#fast mathematical operations over arrays
#linear algebra,fourier transformation,random number generation

In [1]:
!python -m pip install numpy

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'c:\Users\divya\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [61]:
b = np.array([[5,7,8],[7,3,4]])
print(b)
print()
b[0,0] = 88
print(b)
print()
b[1,:] = [14,13,12]
print(b)
print()
b[:,1] = [45,57] #saari rows ke column 1
print(b)
print()
print(b+3) # all values+3

[[5 7 8]
 [7 3 4]]

[[88  7  8]
 [ 7  3  4]]

[[88  7  8]
 [14 13 12]]

[[88 45  8]
 [14 57 12]]

[[91 48 11]
 [17 60 15]]


In [28]:
a=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
print(a.shape)
a

(4, 3)


array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [38]:
print(a[1][0])
print(a[1,0])
print(a[2,0:3:1]) #2nd row, 0 to 3 col ke elements 1 step  par print karega
print(a[2,0:3])
print(a[2,:3])
print(a[2,:])

print(a[:,1])
print(a[:,1:2]) #to maintain dimension we have to use slice only in subscripting

9
9
[11 15 17]
[11 15 17]
[11 15 17]
[11 15 17]
[ 8  3 15 31]
[[ 8]
 [ 3]
 [15]
 [31]]


In [45]:
k = np.array([[[4,8],[3,1],[6,9]],
              [[41,81],[31,11],[61,91]],
              [[1,2],[3,5],[3,4]]])
print(k.shape)
k

(3, 3, 2)


array([[[ 4,  8],
        [ 3,  1],
        [ 6,  9]],

       [[41, 81],
        [31, 11],
        [61, 91]],

       [[ 1,  2],
        [ 3,  5],
        [ 3,  4]]])

In [46]:
#for accessing in array 3 methods:-
#1. indexing
#2. slicing
#3. subscripting

In [47]:
#indexing
k[1][0]

array([41, 81])

In [48]:
#subscripting
k[1,0]  # 1 row, 0 column

array([41, 81])

In [49]:
print(k)

[[[ 4  8]
  [ 3  1]
  [ 6  9]]

 [[41 81]
  [31 11]
  [61 91]]

 [[ 1  2]
  [ 3  5]
  [ 3  4]]]


In [52]:
print(k[:2,-2:,:1]) #starting 2 rows,last 2 column se last tak with step 0: 1 tak
print()
print(k[-1:,-2:,:])  #row,col,step size  
#-1 row se end tak,-2 col se end tak,saare print honge

[[[ 3]
  [ 6]]

 [[31]
  [61]]]

[[[3 5]
  [3 4]]]


In [62]:
a = np.array([[5,7,8],[7,3,4]])
print(a)
print()


[[5 7 8]
 [7 3 4]]



In [65]:
#insert new row
np.append(a,[[1,1,1]], axis = 0) #axis = 0 means row


array([[5, 7, 8],
       [7, 3, 4],
       [1, 1, 1]])

In [68]:
#insert new column
np.append(a,[[1],[1]],axis = 1)
# but abhi yeh sab jo humne append kiya hai woh kahi save nhi hua hai toh agar hum print(a) karenge toh hume original array
#hi milegi or save karne ke liye hume a= np. append karna padega

array([[5, 7, 8, 1],
       [7, 3, 4, 1]])

In [69]:
np.delete(a,1,axis=1) # delete column 1

array([[5, 8],
       [7, 4]])

In [71]:
np.delete(a,1,axis=0) #delete row 1

array([[5, 7, 8]])

In [98]:
#array creation functions
# np.array()
# np.arange()
# np.linspace()
# np.ones()
# np.zeros()
# np.eye()
# np.random.randint()

In [ ]:
# DAY 2 NUMPY CONTINUED....

In [4]:
import numpy as np

In [5]:
m = np.array([1,2,3])
m

array([1, 2, 3])

In [41]:
np.arange(1,11,1)
np.arange(1,11,1.5) #can give float number in range function

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [7]:
list(range(1,11,1)) #can't give float number in range function

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
np.linspace(1,10,10) #Return evenly spaced numbers over a specified interval. 
#Returns num evenly spaced samples, calculated over the interval [start, stop].
#given 10 evenly spaced number between 1 to 10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.ones([4,5]) #default type float
np.ones([4,5],dtype=int) #to convert into int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
p = np.ones([4,5])
p

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
p.dtype

dtype('float64')

In [31]:
p.astype(int)  #to typecast
#does not typecst in original data until we assign it to some variable

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
p 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
p8 = p.astype('uint8')   #typecast into unsigned int of 8 byte
p8

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [ ]:
# 'uint8','uint16','uint32','uint64'
# 'int8','int16','int32','int64'
# 'float8','float16','float32','float64'


In [13]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.eye(4) #Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4,dtype=int)
np.eye(4,dtype=str)

array([['1', '', '', ''],
       ['', '1', '', ''],
       ['', '', '1', ''],
       ['', '', '', '1']], dtype='<U1')

In [38]:
np.random.randint(1,100,5) #gives 5 random integer values between 1 to 100

array([12, 24, 59, 42, 42])

In [49]:
np.random.randint(1,100,[3,5])

array([[45, 78, 76, 66, 48],
       [31, 85, 87, 19, 10],
       [42, 63,  2, 83, 17]])

In [57]:
np.random.seed(55) #to contol randomness now next type when we run the below function we get the same array. we can write 
#any number inside seed
np.random.randint(1,100,[3,5])
#next time if we want same array even by randomint use the same seed value that can be any value in this case it is 55

array([[78, 27, 40, 73, 30],
       [62, 56, 38, 92, 34],
       [55, 36, 47, 95, 62]])

In [58]:
np.random.seed(55)
np.random.randint(1,99,[3,5])

array([[78, 27, 40, 73, 30],
       [62, 56, 38, 92, 34],
       [55, 36, 47, 95, 62]])

In [66]:
r =np.random.rand(3,4) *100# The dimensions of the returned array, must be non-negative.
#If no argument is given a single Python float is returned.
r #*100 meand numbers until 100

array([[39.78872732, 61.48164945, 31.74165027, 80.59605396],
       [60.27508995, 69.07932281, 84.72765018,  3.28256202],
       [75.70030729, 91.47003262, 38.5475965 ,  1.40621047]])

In [68]:
np.random.randn(3,4) #gives negative number

array([[ 1.14629152, -0.59080227,  0.76964903,  1.54264363],
       [-0.6439006 ,  0.91121849,  0.98734657, -1.76455755],
       [ 0.63761005,  2.24598096, -0.67247549,  1.5638072 ]])

In [72]:
np.loadtxt('data.txt',dtype='str') #data.txt ko load karke usko string me convert kiya hai

array([['This', 'is', 'a', 'new', 'file', 'with', 'some', 'data', 'and'],
       ['we', 'load', 'this', 'using', 'numpy', 'and', 'convert', 'into',
        'array']], dtype='<U7')

In [74]:
np.loadtxt('data1.txt',delimiter=',')

array([[45., 65., 78., 98.],
       [23., 19.,  3., 88.],
       [ 1.,  4.,  5.,  6.]])

In [81]:
a = np.random.randint(1,1000,[3,6])
a

array([[171, 291, 377, 445, 541, 834],
       [397, 280, 147, 988, 607, 474],
       [323, 633, 661, 886,  43, 562]])

In [100]:
np.savetxt('dat3.txt',a,delimiter='|',fmt='%d') #for saving the file in laptop
#%f for saving in float format
#delimiter is a break point which we want between our data

In [84]:
sum(a)  #return column wise sum

array([ 891, 1204, 1185, 2319, 1191, 1870])

In [85]:
sum(sum(a)) #overall sum of a

8660

In [86]:
a.sum()

8660

In [87]:
a.sum(axis=1) #for getting sum of rows axis=1 only for sum function and axis = 0 for column

array([2659, 2893, 3108])

In [92]:
a.mean(axis=1)

array([443.16666667, 482.16666667, 518.        ])

In [89]:
a.max(axis=1) #return har row ki max value

array([834, 988, 886])

In [94]:
a.argmax(axis=1) #return har row ki max value ki index

array([5, 3, 3], dtype=int64)

In [95]:
a

array([[171, 291, 377, 445, 541, 834],
       [397, 280, 147, 988, 607, 474],
       [323, 633, 661, 886,  43, 562]])

In [93]:
a.min(axis=1)

array([171, 147,  43])

In [96]:
a.argmin(axis=1)

array([0, 2, 4], dtype=int64)

In [97]:
a.flatten() #return flatten array

array([171, 291, 377, 445, 541, 834, 397, 280, 147, 988, 607, 474, 323,
       633, 661, 886,  43, 562])

In [99]:
np.where(a>3)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))